name: Playwright Tests
on:
  workflow_dispatch
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        id: install-dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        id: install-playwright-browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
  test:
    name: Tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [install]
    strategy:
      matrix:
        project: [chromium, firefox]
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install Playwright System Dependencies
        id: install-playwright-system-dependencies
        run: npx playwright install-deps ${{ matrix.project }}
      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          ENV: local
          PWTEST_BLOB_REPORT_NAME: ${{ matrix.project }}
      - name: Upload Playwright Blob Report
        id: upload-playwright-blob-report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-all-blob-reports
          path: playwright-blob-report
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload allure results
        id: upload-allure-results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results-${{ matrix.project }}-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: allure-results/
          if-no-files-found: ignore
          retention-days: 1
  report:
    name: Create report
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test]
    timeout-minutes: 30
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v3
        # with:
        #   path:
        #     allure-results/
      # - name: Move artifacts to appropriate folders
      #   id: move-to-allure-reports-folder
      #   run: |
      #     mv allure-results/playwright-all-blob-reports ./
      #   shell: bash
      # - name: Download Artifacts
      #   id: download-artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: playwright-all-blob-reports
      #     path: playwright-report/
      - name: Merge Playwright HTML Reports
        id: merge-playwright-html-reports
        run: npx playwright merge-reports --reporter html ./playwright-all-blob-reports
      # - name: Download Artifacts
      #   id: download-artifacts-allure1
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: allure-results-chromium-1_2
      #     path: allure-results/
      # - name: Download Artifacts
      #   id: download-artifacts-allure2
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: allure-results-chromium-2_2
      #     path: allure-results/
      # - name: Download Artifacts
      #   id: download-artifacts-allure3
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: allure-results-firefox-1_2
      #     path: allure-results/
      # - name: Download Artifacts
      #   id: download-artifacts-allure4
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: allure-results-firefox-2_2
      #     path: allure-results/
      - name: Create Unpacked Directory
        run: |
          # Create a directory to store the unpacked results
          mkdir -p allure-results
      - name: Move artifacts to appropriate folders
        id: move-to-allure-results
        run: |
          mv allure-results-chromium-1_2/* allure-results/
          mv allure-results-chromium-2_2/* allure-results/
          mv allure-results-firefox-1_2/* allure-results/
          mv allure-results-firefox-2_2/* allure-results/
        shell: bash
      - name: List Artifact Files
        run: |
          # List the contents of the downloaded artifact
          ls -l allure-results
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results/
          #gh_pages: gh-pages
          allure_report: reports/allure-report
          allure_history: reports/allure-history
      - name: Move to Reports folder
        id: move-to-reports-folder
        run: |
          mv playwright-report reports/playwright
        shell: bash
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v3
      - name: Upload Pages Artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: reports/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Delete Unnecessary Artifacts
        id: delete-unnecessary-artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            playwright-report-*
            test-results-*
            monocart-report-*
          failOnError: false

